export let easyMap = {
  start: [0, 0],
  end: [2, 2],
  name: "Easy Map",
  map: [
    [
      {
        enabled: true,
        directions: { north: false, south: false, east: true, west: false },
        entities: [
          {
            name: "sting",
            value: 5,
            type: "weapon",
            enabled: true,
            symbol: "sword",
            seen: false,
          },
          {
            name: "Jack",
            value: 3,
            type: "enemy",
            enabled: false,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "diamond ring",
            value: 6,
            type: "item",
            enabled: true,
            symbol: "ring",
            seen: false,
          },
          {
            name: "platinum coin",
            value: 5,
            type: "item",
            enabled: false,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "locked gate",
            value: 3,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
        ],
      },
      {
        enabled: true,
        directions: { north: false, south: true, east: true, west: true },
        entities: [
          {
            name: "sting",
            value: 5,
            type: "weapon",
            enabled: true,
            symbol: "sword",
            seen: false,
          },
          {
            name: "Jack",
            value: 3,
            type: "enemy",
            enabled: false,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "diamond ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "platinum coin",
            value: 5,
            type: "item",
            enabled: true,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "locked gate",
            value: 3,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
        ],
      },
      {
        enabled: true,
        directions: { north: false, south: false, east: false, west: true },
        entities: [
          {
            name: "sting",
            value: 5,
            type: "weapon",
            enabled: true,
            symbol: "sword",
            seen: false,
          },
          {
            name: "Jack",
            value: 3,
            type: "enemy",
            enabled: true,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "diamond ring",
            value: 6,
            type: "item",
            enabled: true,
            symbol: "ring",
            seen: false,
          },
          {
            name: "platinum coin",
            value: 5,
            type: "item",
            enabled: true,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: true,
            symbol: "key",
            seen: false,
          },
          {
            name: "locked gate",
            value: 3,
            type: "obstacle",
            enabled: true,
            symbol: "door",
            seen: false,
          },
        ],
      },
    ],
    [
      {
        enabled: false,
        directions: { north: false, south: false, east: false, west: false },
        entities: [
          {
            name: "sting",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "sword",
            seen: false,
          },
          {
            name: "Jack",
            value: 3,
            type: "enemy",
            enabled: false,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "diamond ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "platinum coin",
            value: 5,
            type: "item",
            enabled: false,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "locked gate",
            value: 3,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
        ],
      },
      {
        enabled: true,
        directions: { north: true, south: true, east: false, west: false },
        entities: [
          {
            name: "sting",
            value: 5,
            type: "weapon",
            enabled: true,
            symbol: "sword",
            seen: false,
          },
          {
            name: "Jack",
            value: 3,
            type: "enemy",
            enabled: true,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "diamond ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "platinum coin",
            value: 5,
            type: "item",
            enabled: false,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "locked gate",
            value: 3,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
        ],
      },
      {
        enabled: false,
        directions: { north: false, south: false, east: false, west: false },
        entities: [
          {
            name: "sting",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "sword",
            seen: false,
          },
          {
            name: "Jack",
            value: 3,
            type: "enemy",
            enabled: false,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "diamond ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "platinum coin",
            value: 5,
            type: "item",
            enabled: false,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "locked gate",
            value: 3,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
        ],
      },
    ],
    [
      {
        enabled: true,
        directions: { north: false, south: false, east: true, west: false },
        entities: [
          {
            name: "sting",
            value: 5,
            type: "weapon",
            enabled: true,
            symbol: "sword",
            seen: false,
          },
          {
            name: "Jack",
            value: 3,
            type: "enemy",
            enabled: true,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "diamond ring",
            value: 6,
            type: "item",
            enabled: true,
            symbol: "ring",
            seen: false,
          },
          {
            name: "platinum coin",
            value: 5,
            type: "item",
            enabled: true,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: true,
            symbol: "key",
            seen: false,
          },
          {
            name: "locked gate",
            value: 3,
            type: "obstacle",
            enabled: true,
            symbol: "door",
            seen: false,
          },
        ],
      },
      {
        enabled: true,
        directions: { north: true, south: false, east: true, west: true },
        entities: [
          {
            name: "sting",
            value: 5,
            type: "weapon",
            enabled: true,
            symbol: "sword",
            seen: false,
          },
          {
            name: "Jack",
            value: 3,
            type: "enemy",
            enabled: false,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "diamond ring",
            value: 6,
            type: "item",
            enabled: true,
            symbol: "ring",
            seen: false,
          },
          {
            name: "platinum coin",
            value: 5,
            type: "item",
            enabled: true,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "locked gate",
            value: 3,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
        ],
      },
      {
        enabled: true,
        directions: { north: false, south: false, east: false, west: true },
        entities: [
          {
            name: "sting",
            value: 5,
            type: "weapon",
            enabled: true,
            symbol: "sword",
            seen: false,
          },
          {
            name: "Jack",
            value: 3,
            type: "enemy",
            enabled: false,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "diamond ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "platinum coin",
            value: 5,
            type: "item",
            enabled: true,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "locked gate",
            value: 3,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
        ],
      },
    ],
  ],
};
