export let hardMap = {
  start: [2, 2],
  end: [1, 2],
  name: "hardMap",
  map: [
    [
      {
        enabled: true,
        directions: { north: false, south: true, east: true, west: false },
        entities: [
          {
            name: "longsword",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "sword",
            seen: false,
          },
          {
            name: "kite shield",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "shield",
            seen: false,
          },
          {
            name: "plate armour",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "armour",
            seen: false,
          },
          {
            name: "evil knight",
            value: 5,
            type: "enemy",
            enabled: false,
            symbol: "knight",
            seen: false,
          },
          {
            name: "scary zombie",
            value: 4,
            type: "enemy",
            enabled: true,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "hellfire dragon",
            value: 6,
            type: "enemy",
            enabled: false,
            symbol: "dragon",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: true,
            symbol: "ring",
            seen: false,
          },
          {
            name: "bag of gold",
            value: 6,
            type: "item",
            enabled: true,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "studded door",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
          {
            name: "wall of stone",
            value: 6,
            type: "obstacle",
            enabled: false,
            symbol: "castle",
            seen: false,
          },
          {
            name: "ancient lock",
            value: 4,
            type: "obstacle",
            enabled: true,
            symbol: "lock",
            seen: false,
          },
        ],
      },
      {
        enabled: true,
        directions: { north: false, south: false, east: true, west: true },
        entities: [
          {
            name: "longsword",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "sword",
            seen: false,
          },
          {
            name: "kite shield",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "shield",
            seen: false,
          },
          {
            name: "plate armour",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "armour",
            seen: false,
          },
          {
            name: "evil knight",
            value: 5,
            type: "enemy",
            enabled: false,
            symbol: "knight",
            seen: false,
          },
          {
            name: "scary zombie",
            value: 4,
            type: "enemy",
            enabled: true,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "hellfire dragon",
            value: 6,
            type: "enemy",
            enabled: false,
            symbol: "dragon",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: true,
            symbol: "ring",
            seen: false,
          },
          {
            name: "bag of gold",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: true,
            symbol: "key",
            seen: false,
          },
          {
            name: "studded door",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
          {
            name: "wall of stone",
            value: 6,
            type: "obstacle",
            enabled: false,
            symbol: "castle",
            seen: false,
          },
          {
            name: "ancient lock",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "lock",
            seen: false,
          },
        ],
      },
      {
        enabled: true,
        directions: { north: false, south: true, east: true, west: true },
        entities: [
          {
            name: "longsword",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "sword",
            seen: false,
          },
          {
            name: "kite shield",
            value: 5,
            type: "weapon",
            enabled: true,
            symbol: "shield",
            seen: false,
          },
          {
            name: "plate armour",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "armour",
            seen: false,
          },
          {
            name: "evil knight",
            value: 5,
            type: "enemy",
            enabled: false,
            symbol: "knight",
            seen: false,
          },
          {
            name: "scary zombie",
            value: 4,
            type: "enemy",
            enabled: false,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "hellfire dragon",
            value: 6,
            type: "enemy",
            enabled: true,
            symbol: "dragon",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "bag of gold",
            value: 6,
            type: "item",
            enabled: true,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "studded door",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
          {
            name: "wall of stone",
            value: 6,
            type: "obstacle",
            enabled: false,
            symbol: "castle",
            seen: false,
          },
          {
            name: "ancient lock",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "lock",
            seen: false,
          },
        ],
      },
      {
        enabled: true,
        directions: { north: false, south: false, east: true, west: true },
        entities: [
          {
            name: "longsword",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "sword",
            seen: false,
          },
          {
            name: "kite shield",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "shield",
            seen: false,
          },
          {
            name: "plate armour",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "armour",
            seen: false,
          },
          {
            name: "evil knight",
            value: 5,
            type: "enemy",
            enabled: true,
            symbol: "knight",
            seen: false,
          },
          {
            name: "scary zombie",
            value: 4,
            type: "enemy",
            enabled: false,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "hellfire dragon",
            value: 6,
            type: "enemy",
            enabled: false,
            symbol: "dragon",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "bag of gold",
            value: 6,
            type: "item",
            enabled: true,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: true,
            symbol: "key",
            seen: false,
          },
          {
            name: "studded door",
            value: 4,
            type: "obstacle",
            enabled: true,
            symbol: "door",
            seen: false,
          },
          {
            name: "wall of stone",
            value: 6,
            type: "obstacle",
            enabled: false,
            symbol: "castle",
            seen: false,
          },
          {
            name: "ancient lock",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "lock",
            seen: false,
          },
        ],
      },
      {
        enabled: true,
        directions: { north: false, south: false, east: false, west: false },
        entities: [
          {
            name: "longsword",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "sword",
            seen: false,
          },
          {
            name: "kite shield",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "shield",
            seen: false,
          },
          {
            name: "plate armour",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "armour",
            seen: false,
          },
          {
            name: "evil knight",
            value: 5,
            type: "enemy",
            enabled: false,
            symbol: "knight",
            seen: false,
          },
          {
            name: "scary zombie",
            value: 4,
            type: "enemy",
            enabled: false,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "hellfire dragon",
            value: 6,
            type: "enemy",
            enabled: true,
            symbol: "dragon",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "bag of gold",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "studded door",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
          {
            name: "wall of stone",
            value: 6,
            type: "obstacle",
            enabled: false,
            symbol: "castle",
            seen: false,
          },
          {
            name: "ancient lock",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "lock",
            seen: false,
          },
        ],
      },
    ],
    [
      {
        enabled: true,
        directions: { north: true, south: true, east: false, west: false },
        entities: [
          {
            name: "longsword",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "sword",
            seen: false,
          },
          {
            name: "kite shield",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "shield",
            seen: false,
          },
          {
            name: "plate armour",
            value: 5,
            type: "weapon",
            enabled: true,
            symbol: "armour",
            seen: false,
          },
          {
            name: "evil knight",
            value: 5,
            type: "enemy",
            enabled: false,
            symbol: "knight",
            seen: false,
          },
          {
            name: "scary zombie",
            value: 4,
            type: "enemy",
            enabled: true,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "hellfire dragon",
            value: 6,
            type: "enemy",
            enabled: false,
            symbol: "dragon",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "bag of gold",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "studded door",
            value: 4,
            type: "obstacle",
            enabled: true,
            symbol: "door",
            seen: false,
          },
          {
            name: "wall of stone",
            value: 6,
            type: "obstacle",
            enabled: false,
            symbol: "castle",
            seen: false,
          },
          {
            name: "ancient lock",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "lock",
            seen: false,
          },
        ],
      },
      {
        enabled: false,
        directions: { north: false, south: false, east: false, west: false },
        entities: [
          {
            name: "longsword",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "sword",
            seen: false,
          },
          {
            name: "kite shield",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "shield",
            seen: false,
          },
          {
            name: "plate armour",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "armour",
            seen: false,
          },
          {
            name: "evil knight",
            value: 5,
            type: "enemy",
            enabled: false,
            symbol: "knight",
            seen: false,
          },
          {
            name: "scary zombie",
            value: 4,
            type: "enemy",
            enabled: false,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "hellfire dragon",
            value: 6,
            type: "enemy",
            enabled: false,
            symbol: "dragon",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "bag of gold",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "studded door",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
          {
            name: "wall of stone",
            value: 6,
            type: "obstacle",
            enabled: false,
            symbol: "castle",
            seen: false,
          },
          {
            name: "ancient lock",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "lock",
            seen: false,
          },
        ],
      },
      {
        enabled: true,
        directions: { north: true, south: false, east: false, west: false },
        entities: [
          {
            name: "longsword",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "sword",
            seen: false,
          },
          {
            name: "kite shield",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "shield",
            seen: false,
          },
          {
            name: "plate armour",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "armour",
            seen: false,
          },
          {
            name: "evil knight",
            value: 5,
            type: "enemy",
            enabled: false,
            symbol: "knight",
            seen: false,
          },
          {
            name: "scary zombie",
            value: 4,
            type: "enemy",
            enabled: false,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "hellfire dragon",
            value: 6,
            type: "enemy",
            enabled: false,
            symbol: "dragon",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "bag of gold",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "studded door",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
          {
            name: "wall of stone",
            value: 6,
            type: "obstacle",
            enabled: false,
            symbol: "castle",
            seen: false,
          },
          {
            name: "ancient lock",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "lock",
            seen: false,
          },
        ],
      },
      {
        enabled: false,
        directions: { north: false, south: false, east: false, west: false },
        entities: [
          {
            name: "longsword",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "sword",
            seen: false,
          },
          {
            name: "kite shield",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "shield",
            seen: false,
          },
          {
            name: "plate armour",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "armour",
            seen: false,
          },
          {
            name: "evil knight",
            value: 5,
            type: "enemy",
            enabled: false,
            symbol: "knight",
            seen: false,
          },
          {
            name: "scary zombie",
            value: 4,
            type: "enemy",
            enabled: false,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "hellfire dragon",
            value: 6,
            type: "enemy",
            enabled: false,
            symbol: "dragon",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "bag of gold",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "studded door",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
          {
            name: "wall of stone",
            value: 6,
            type: "obstacle",
            enabled: false,
            symbol: "castle",
            seen: false,
          },
          {
            name: "ancient lock",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "lock",
            seen: false,
          },
        ],
      },
      {
        enabled: false,
        directions: { north: false, south: false, east: false, west: false },
        entities: [
          {
            name: "longsword",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "sword",
            seen: false,
          },
          {
            name: "kite shield",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "shield",
            seen: false,
          },
          {
            name: "plate armour",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "armour",
            seen: false,
          },
          {
            name: "evil knight",
            value: 5,
            type: "enemy",
            enabled: false,
            symbol: "knight",
            seen: false,
          },
          {
            name: "scary zombie",
            value: 4,
            type: "enemy",
            enabled: false,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "hellfire dragon",
            value: 6,
            type: "enemy",
            enabled: false,
            symbol: "dragon",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "bag of gold",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "studded door",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
          {
            name: "wall of stone",
            value: 6,
            type: "obstacle",
            enabled: false,
            symbol: "castle",
            seen: false,
          },
          {
            name: "ancient lock",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "lock",
            seen: false,
          },
        ],
      },
    ],
    [
      {
        enabled: true,
        directions: { north: true, south: false, east: true, west: false },
        entities: [
          {
            name: "longsword",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "sword",
            seen: false,
          },
          {
            name: "kite shield",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "shield",
            seen: false,
          },
          {
            name: "plate armour",
            value: 5,
            type: "weapon",
            enabled: true,
            symbol: "armour",
            seen: false,
          },
          {
            name: "evil knight",
            value: 5,
            type: "enemy",
            enabled: false,
            symbol: "knight",
            seen: false,
          },
          {
            name: "scary zombie",
            value: 4,
            type: "enemy",
            enabled: false,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "hellfire dragon",
            value: 6,
            type: "enemy",
            enabled: true,
            symbol: "dragon",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "bag of gold",
            value: 6,
            type: "item",
            enabled: true,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "studded door",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
          {
            name: "wall of stone",
            value: 6,
            type: "obstacle",
            enabled: false,
            symbol: "castle",
            seen: false,
          },
          {
            name: "ancient lock",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "lock",
            seen: false,
          },
        ],
      },
      {
        enabled: true,
        directions: { north: false, south: true, east: true, west: true },
        entities: [
          {
            name: "longsword",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "sword",
            seen: false,
          },
          {
            name: "kite shield",
            value: 5,
            type: "weapon",
            enabled: true,
            symbol: "shield",
            seen: false,
          },
          {
            name: "plate armour",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "armour",
            seen: false,
          },
          {
            name: "evil knight",
            value: 5,
            type: "enemy",
            enabled: false,
            symbol: "knight",
            seen: false,
          },
          {
            name: "scary zombie",
            value: 4,
            type: "enemy",
            enabled: true,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "hellfire dragon",
            value: 6,
            type: "enemy",
            enabled: false,
            symbol: "dragon",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "bag of gold",
            value: 6,
            type: "item",
            enabled: true,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "studded door",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
          {
            name: "wall of stone",
            value: 6,
            type: "obstacle",
            enabled: false,
            symbol: "castle",
            seen: false,
          },
          {
            name: "ancient lock",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "lock",
            seen: false,
          },
        ],
      },
      {
        enabled: true,
        directions: { north: false, south: true, east: true, west: true },
        entities: [
          {
            name: "longsword",
            value: 5,
            type: "weapon",
            enabled: true,
            symbol: "sword",
            seen: false,
          },
          {
            name: "kite shield",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "shield",
            seen: false,
          },
          {
            name: "plate armour",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "armour",
            seen: false,
          },
          {
            name: "evil knight",
            value: 5,
            type: "enemy",
            enabled: false,
            symbol: "knight",
            seen: false,
          },
          {
            name: "scary zombie",
            value: 4,
            type: "enemy",
            enabled: true,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "hellfire dragon",
            value: 6,
            type: "enemy",
            enabled: false,
            symbol: "dragon",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "bag of gold",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "studded door",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
          {
            name: "wall of stone",
            value: 6,
            type: "obstacle",
            enabled: false,
            symbol: "castle",
            seen: false,
          },
          {
            name: "ancient lock",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "lock",
            seen: false,
          },
        ],
      },
      {
        enabled: true,
        directions: { north: false, south: false, east: true, west: true },
        entities: [
          {
            name: "longsword",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "sword",
            seen: false,
          },
          {
            name: "kite shield",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "shield",
            seen: false,
          },
          {
            name: "plate armour",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "armour",
            seen: false,
          },
          {
            name: "evil knight",
            value: 5,
            type: "enemy",
            enabled: true,
            symbol: "knight",
            seen: false,
          },
          {
            name: "scary zombie",
            value: 4,
            type: "enemy",
            enabled: true,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "hellfire dragon",
            value: 6,
            type: "enemy",
            enabled: false,
            symbol: "dragon",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "bag of gold",
            value: 6,
            type: "item",
            enabled: true,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "studded door",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
          {
            name: "wall of stone",
            value: 6,
            type: "obstacle",
            enabled: false,
            symbol: "castle",
            seen: false,
          },
          {
            name: "ancient lock",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "lock",
            seen: false,
          },
        ],
      },
      {
        enabled: true,
        directions: { north: false, south: true, east: false, west: true },
        entities: [
          {
            name: "longsword",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "sword",
            seen: false,
          },
          {
            name: "kite shield",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "shield",
            seen: false,
          },
          {
            name: "plate armour",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "armour",
            seen: false,
          },
          {
            name: "evil knight",
            value: 5,
            type: "enemy",
            enabled: false,
            symbol: "knight",
            seen: false,
          },
          {
            name: "scary zombie",
            value: 4,
            type: "enemy",
            enabled: true,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "hellfire dragon",
            value: 6,
            type: "enemy",
            enabled: false,
            symbol: "dragon",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: true,
            symbol: "ring",
            seen: false,
          },
          {
            name: "bag of gold",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "studded door",
            value: 4,
            type: "obstacle",
            enabled: true,
            symbol: "door",
            seen: false,
          },
          {
            name: "wall of stone",
            value: 6,
            type: "obstacle",
            enabled: true,
            symbol: "castle",
            seen: false,
          },
          {
            name: "ancient lock",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "lock",
            seen: false,
          },
        ],
      },
    ],
    [
      {
        enabled: true,
        directions: { north: true, south: false, east: true, west: false },
        entities: [
          {
            name: "longsword",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "sword",
            seen: false,
          },
          {
            name: "kite shield",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "shield",
            seen: false,
          },
          {
            name: "plate armour",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "armour",
            seen: false,
          },
          {
            name: "evil knight",
            value: 5,
            type: "enemy",
            enabled: false,
            symbol: "knight",
            seen: false,
          },
          {
            name: "scary zombie",
            value: 4,
            type: "enemy",
            enabled: false,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "hellfire dragon",
            value: 6,
            type: "enemy",
            enabled: false,
            symbol: "dragon",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "bag of gold",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "studded door",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
          {
            name: "wall of stone",
            value: 6,
            type: "obstacle",
            enabled: false,
            symbol: "castle",
            seen: false,
          },
          {
            name: "ancient lock",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "lock",
            seen: false,
          },
        ],
      },
      {
        enabled: true,
        directions: { north: false, south: true, east: true, west: true },
        entities: [
          {
            name: "longsword",
            value: 5,
            type: "weapon",
            enabled: true,
            symbol: "sword",
            seen: false,
          },
          {
            name: "kite shield",
            value: 5,
            type: "weapon",
            enabled: true,
            symbol: "shield",
            seen: false,
          },
          {
            name: "plate armour",
            value: 5,
            type: "weapon",
            enabled: true,
            symbol: "armour",
            seen: false,
          },
          {
            name: "evil knight",
            value: 5,
            type: "enemy",
            enabled: false,
            symbol: "knight",
            seen: false,
          },
          {
            name: "scary zombie",
            value: 4,
            type: "enemy",
            enabled: false,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "hellfire dragon",
            value: 6,
            type: "enemy",
            enabled: false,
            symbol: "dragon",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: true,
            symbol: "ring",
            seen: false,
          },
          {
            name: "bag of gold",
            value: 6,
            type: "item",
            enabled: true,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "studded door",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
          {
            name: "wall of stone",
            value: 6,
            type: "obstacle",
            enabled: false,
            symbol: "castle",
            seen: false,
          },
          {
            name: "ancient lock",
            value: 4,
            type: "obstacle",
            enabled: true,
            symbol: "lock",
            seen: false,
          },
        ],
      },
      {
        enabled: true,
        directions: { north: true, south: true, east: false, west: true },
        entities: [
          {
            name: "longsword",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "sword",
            seen: false,
          },
          {
            name: "kite shield",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "shield",
            seen: false,
          },
          {
            name: "plate armour",
            value: 5,
            type: "weapon",
            enabled: true,
            symbol: "armour",
            seen: false,
          },
          {
            name: "evil knight",
            value: 5,
            type: "enemy",
            enabled: false,
            symbol: "knight",
            seen: false,
          },
          {
            name: "scary zombie",
            value: 4,
            type: "enemy",
            enabled: true,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "hellfire dragon",
            value: 6,
            type: "enemy",
            enabled: false,
            symbol: "dragon",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "bag of gold",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "studded door",
            value: 4,
            type: "obstacle",
            enabled: true,
            symbol: "door",
            seen: false,
          },
          {
            name: "wall of stone",
            value: 6,
            type: "obstacle",
            enabled: false,
            symbol: "castle",
            seen: false,
          },
          {
            name: "ancient lock",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "lock",
            seen: false,
          },
        ],
      },
      {
        enabled: false,
        directions: { north: false, south: false, east: false, west: false },
        entities: [
          {
            name: "longsword",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "sword",
            seen: false,
          },
          {
            name: "kite shield",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "shield",
            seen: false,
          },
          {
            name: "plate armour",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "armour",
            seen: false,
          },
          {
            name: "evil knight",
            value: 5,
            type: "enemy",
            enabled: false,
            symbol: "knight",
            seen: false,
          },
          {
            name: "scary zombie",
            value: 4,
            type: "enemy",
            enabled: false,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "hellfire dragon",
            value: 6,
            type: "enemy",
            enabled: false,
            symbol: "dragon",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "bag of gold",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "studded door",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
          {
            name: "wall of stone",
            value: 6,
            type: "obstacle",
            enabled: false,
            symbol: "castle",
            seen: false,
          },
          {
            name: "ancient lock",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "lock",
            seen: false,
          },
        ],
      },
      {
        enabled: true,
        directions: { north: true, south: false, east: false, west: false },
        entities: [
          {
            name: "longsword",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "sword",
            seen: false,
          },
          {
            name: "kite shield",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "shield",
            seen: false,
          },
          {
            name: "plate armour",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "armour",
            seen: false,
          },
          {
            name: "evil knight",
            value: 5,
            type: "enemy",
            enabled: true,
            symbol: "knight",
            seen: false,
          },
          {
            name: "scary zombie",
            value: 4,
            type: "enemy",
            enabled: true,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "hellfire dragon",
            value: 6,
            type: "enemy",
            enabled: false,
            symbol: "dragon",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "bag of gold",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "studded door",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
          {
            name: "wall of stone",
            value: 6,
            type: "obstacle",
            enabled: false,
            symbol: "castle",
            seen: false,
          },
          {
            name: "ancient lock",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "lock",
            seen: false,
          },
        ],
      },
    ],
    [
      {
        enabled: false,
        directions: { north: false, south: false, east: false, west: false },
        entities: [
          {
            name: "longsword",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "sword",
            seen: false,
          },
          {
            name: "kite shield",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "shield",
            seen: false,
          },
          {
            name: "plate armour",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "armour",
            seen: false,
          },
          {
            name: "evil knight",
            value: 5,
            type: "enemy",
            enabled: false,
            symbol: "knight",
            seen: false,
          },
          {
            name: "scary zombie",
            value: 4,
            type: "enemy",
            enabled: false,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "hellfire dragon",
            value: 6,
            type: "enemy",
            enabled: false,
            symbol: "dragon",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "bag of gold",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "studded door",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
          {
            name: "wall of stone",
            value: 6,
            type: "obstacle",
            enabled: false,
            symbol: "castle",
            seen: false,
          },
          {
            name: "ancient lock",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "lock",
            seen: false,
          },
        ],
      },
      {
        enabled: true,
        directions: { north: true, south: false, east: true, west: false },
        entities: [
          {
            name: "longsword",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "sword",
            seen: false,
          },
          {
            name: "kite shield",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "shield",
            seen: false,
          },
          {
            name: "plate armour",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "armour",
            seen: false,
          },
          {
            name: "evil knight",
            value: 5,
            type: "enemy",
            enabled: true,
            symbol: "knight",
            seen: false,
          },
          {
            name: "scary zombie",
            value: 4,
            type: "enemy",
            enabled: true,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "hellfire dragon",
            value: 6,
            type: "enemy",
            enabled: false,
            symbol: "dragon",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: true,
            symbol: "ring",
            seen: false,
          },
          {
            name: "bag of gold",
            value: 6,
            type: "item",
            enabled: true,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "studded door",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
          {
            name: "wall of stone",
            value: 6,
            type: "obstacle",
            enabled: false,
            symbol: "castle",
            seen: false,
          },
          {
            name: "ancient lock",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "lock",
            seen: false,
          },
        ],
      },
      {
        enabled: true,
        directions: { north: true, south: false, east: true, west: true },
        entities: [
          {
            name: "longsword",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "sword",
            seen: false,
          },
          {
            name: "kite shield",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "shield",
            seen: false,
          },
          {
            name: "plate armour",
            value: 5,
            type: "weapon",
            enabled: true,
            symbol: "armour",
            seen: false,
          },
          {
            name: "evil knight",
            value: 5,
            type: "enemy",
            enabled: false,
            symbol: "knight",
            seen: false,
          },
          {
            name: "scary zombie",
            value: 4,
            type: "enemy",
            enabled: true,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "hellfire dragon",
            value: 6,
            type: "enemy",
            enabled: false,
            symbol: "dragon",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "bag of gold",
            value: 6,
            type: "item",
            enabled: true,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "studded door",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
          {
            name: "wall of stone",
            value: 6,
            type: "obstacle",
            enabled: false,
            symbol: "castle",
            seen: false,
          },
          {
            name: "ancient lock",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "lock",
            seen: false,
          },
        ],
      },
      {
        enabled: true,
        directions: { north: false, south: false, east: true, west: true },
        entities: [
          {
            name: "longsword",
            value: 5,
            type: "weapon",
            enabled: true,
            symbol: "sword",
            seen: false,
          },
          {
            name: "kite shield",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "shield",
            seen: false,
          },
          {
            name: "plate armour",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "armour",
            seen: false,
          },
          {
            name: "evil knight",
            value: 5,
            type: "enemy",
            enabled: true,
            symbol: "knight",
            seen: false,
          },
          {
            name: "scary zombie",
            value: 4,
            type: "enemy",
            enabled: true,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "hellfire dragon",
            value: 6,
            type: "enemy",
            enabled: false,
            symbol: "dragon",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: true,
            symbol: "ring",
            seen: false,
          },
          {
            name: "bag of gold",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "studded door",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
          {
            name: "wall of stone",
            value: 6,
            type: "obstacle",
            enabled: false,
            symbol: "castle",
            seen: false,
          },
          {
            name: "ancient lock",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "lock",
            seen: false,
          },
        ],
      },
      {
        enabled: true,
        directions: { north: true, south: false, east: false, west: false },
        entities: [
          {
            name: "longsword",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "sword",
            seen: false,
          },
          {
            name: "kite shield",
            value: 5,
            type: "weapon",
            enabled: false,
            symbol: "shield",
            seen: false,
          },
          {
            name: "plate armour",
            value: 5,
            type: "weapon",
            enabled: true,
            symbol: "armour",
            seen: false,
          },
          {
            name: "evil knight",
            value: 5,
            type: "enemy",
            enabled: false,
            symbol: "knight",
            seen: false,
          },
          {
            name: "scary zombie",
            value: 4,
            type: "enemy",
            enabled: false,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "hellfire dragon",
            value: 6,
            type: "enemy",
            enabled: true,
            symbol: "dragon",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "bag of gold",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "studded door",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
          {
            name: "wall of stone",
            value: 6,
            type: "obstacle",
            enabled: true,
            symbol: "castle",
            seen: false,
          },
          {
            name: "ancient lock",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "lock",
            seen: false,
          },
        ],
      },
    ],
  ],
};
