export let mediumMap = {
  start: [0, 3],
  end: [3, 2],
  name: "mediumMap",
  map: [
    [
      {
        enabled: true,
        directions: { north: false, south: false, east: true, west: false },
        entities: [
          {
            name: "rusty blade",
            value: 4,
            type: "weapon",
            enabled: true,
            symbol: "sword",
            seen: false,
          },
          {
            name: "battered shield",
            value: 4,
            type: "weapon",
            enabled: false,
            symbol: "shield",
            seen: false,
          },
          {
            name: "green knight",
            value: 5,
            type: "enemy",
            enabled: false,
            symbol: "knight",
            seen: false,
          },
          {
            name: "evil skeleton",
            value: 4,
            type: "enemy",
            enabled: false,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "gold florin ",
            value: 4,
            type: "item",
            enabled: false,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "portcullis ",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
          {
            name: "rusty lock",
            value: 6,
            type: "obstacle",
            enabled: false,
            symbol: "lock",
            seen: false,
          },
        ],
      },
      {
        enabled: true,
        directions: { north: false, south: true, east: true, west: true },
        entities: [
          {
            name: "rusty blade",
            value: 4,
            type: "weapon",
            enabled: false,
            symbol: "sword",
            seen: false,
          },
          {
            name: "battered shield",
            value: 4,
            type: "weapon",
            enabled: true,
            symbol: "shield",
            seen: false,
          },
          {
            name: "green knight",
            value: 5,
            type: "enemy",
            enabled: false,
            symbol: "knight",
            seen: false,
          },
          {
            name: "evil skeleton",
            value: 4,
            type: "enemy",
            enabled: false,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "gold florin ",
            value: 4,
            type: "item",
            enabled: false,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "portcullis ",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
          {
            name: "rusty lock",
            value: 6,
            type: "obstacle",
            enabled: false,
            symbol: "lock",
            seen: false,
          },
        ],
      },
      {
        enabled: true,
        directions: { north: false, south: false, east: true, west: true },
        entities: [
          {
            name: "rusty blade",
            value: 4,
            type: "weapon",
            enabled: true,
            symbol: "sword",
            seen: false,
          },
          {
            name: "battered shield",
            value: 4,
            type: "weapon",
            enabled: false,
            symbol: "shield",
            seen: false,
          },
          {
            name: "green knight",
            value: 5,
            type: "enemy",
            enabled: false,
            symbol: "knight",
            seen: false,
          },
          {
            name: "evil skeleton",
            value: 4,
            type: "enemy",
            enabled: true,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "gold florin ",
            value: 4,
            type: "item",
            enabled: false,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "portcullis ",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
          {
            name: "rusty lock",
            value: 6,
            type: "obstacle",
            enabled: true,
            symbol: "lock",
            seen: false,
          },
        ],
      },
      {
        enabled: true,
        directions: { north: false, south: false, east: false, west: true },
        entities: [
          {
            name: "rusty blade",
            value: 4,
            type: "weapon",
            enabled: true,
            symbol: "sword",
            seen: false,
          },
          {
            name: "battered shield",
            value: 4,
            type: "weapon",
            enabled: false,
            symbol: "shield",
            seen: false,
          },
          {
            name: "green knight",
            value: 5,
            type: "enemy",
            enabled: true,
            symbol: "knight",
            seen: false,
          },
          {
            name: "evil skeleton",
            value: 4,
            type: "enemy",
            enabled: true,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "gold florin ",
            value: 4,
            type: "item",
            enabled: false,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: true,
            symbol: "key",
            seen: false,
          },
          {
            name: "portcullis ",
            value: 4,
            type: "obstacle",
            enabled: true,
            symbol: "door",
            seen: false,
          },
          {
            name: "rusty lock",
            value: 6,
            type: "obstacle",
            enabled: false,
            symbol: "lock",
            seen: false,
          },
        ],
      },
    ],
    [
      {
        enabled: false,
        directions: { north: false, south: false, east: false, west: false },
        entities: [
          {
            name: "rusty blade",
            value: 4,
            type: "weapon",
            enabled: false,
            symbol: "sword",
            seen: false,
          },
          {
            name: "battered shield",
            value: 4,
            type: "weapon",
            enabled: false,
            symbol: "shield",
            seen: false,
          },
          {
            name: "green knight",
            value: 5,
            type: "enemy",
            enabled: false,
            symbol: "knight",
            seen: false,
          },
          {
            name: "evil skeleton",
            value: 4,
            type: "enemy",
            enabled: false,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "gold florin ",
            value: 4,
            type: "item",
            enabled: false,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "portcullis ",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
          {
            name: "rusty lock",
            value: 6,
            type: "obstacle",
            enabled: false,
            symbol: "lock",
            seen: false,
          },
        ],
      },
      {
        enabled: true,
        directions: { north: true, south: true, east: false, west: false },
        entities: [
          {
            name: "rusty blade",
            value: 4,
            type: "weapon",
            enabled: false,
            symbol: "sword",
            seen: false,
          },
          {
            name: "battered shield",
            value: 4,
            type: "weapon",
            enabled: true,
            symbol: "shield",
            seen: false,
          },
          {
            name: "green knight",
            value: 5,
            type: "enemy",
            enabled: false,
            symbol: "knight",
            seen: false,
          },
          {
            name: "evil skeleton",
            value: 4,
            type: "enemy",
            enabled: true,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "gold florin ",
            value: 4,
            type: "item",
            enabled: true,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "portcullis ",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
          {
            name: "rusty lock",
            value: 6,
            type: "obstacle",
            enabled: false,
            symbol: "lock",
            seen: false,
          },
        ],
      },
      {
        enabled: false,
        directions: { north: false, south: false, east: false, west: false },
        entities: [
          {
            name: "rusty blade",
            value: 4,
            type: "weapon",
            enabled: false,
            symbol: "sword",
            seen: false,
          },
          {
            name: "battered shield",
            value: 4,
            type: "weapon",
            enabled: false,
            symbol: "shield",
            seen: false,
          },
          {
            name: "green knight",
            value: 5,
            type: "enemy",
            enabled: false,
            symbol: "knight",
            seen: false,
          },
          {
            name: "evil skeleton",
            value: 4,
            type: "enemy",
            enabled: false,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "gold florin ",
            value: 4,
            type: "item",
            enabled: false,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "portcullis ",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
          {
            name: "rusty lock",
            value: 6,
            type: "obstacle",
            enabled: false,
            symbol: "lock",
            seen: false,
          },
        ],
      },
      {
        enabled: false,
        directions: { north: false, south: false, east: false, west: false },
        entities: [
          {
            name: "rusty blade",
            value: 4,
            type: "weapon",
            enabled: false,
            symbol: "sword",
            seen: false,
          },
          {
            name: "battered shield",
            value: 4,
            type: "weapon",
            enabled: false,
            symbol: "shield",
            seen: false,
          },
          {
            name: "green knight",
            value: 5,
            type: "enemy",
            enabled: false,
            symbol: "knight",
            seen: false,
          },
          {
            name: "evil skeleton",
            value: 4,
            type: "enemy",
            enabled: false,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "gold florin ",
            value: 4,
            type: "item",
            enabled: false,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "portcullis ",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
          {
            name: "rusty lock",
            value: 6,
            type: "obstacle",
            enabled: false,
            symbol: "lock",
            seen: false,
          },
        ],
      },
    ],
    [
      {
        enabled: true,
        directions: { north: false, south: false, east: true, west: false },
        entities: [
          {
            name: "rusty blade",
            value: 4,
            type: "weapon",
            enabled: false,
            symbol: "sword",
            seen: false,
          },
          {
            name: "battered shield",
            value: 4,
            type: "weapon",
            enabled: true,
            symbol: "shield",
            seen: false,
          },
          {
            name: "green knight",
            value: 5,
            type: "enemy",
            enabled: true,
            symbol: "knight",
            seen: false,
          },
          {
            name: "evil skeleton",
            value: 4,
            type: "enemy",
            enabled: true,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "gold florin ",
            value: 4,
            type: "item",
            enabled: true,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: true,
            symbol: "key",
            seen: false,
          },
          {
            name: "portcullis ",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
          {
            name: "rusty lock",
            value: 6,
            type: "obstacle",
            enabled: false,
            symbol: "lock",
            seen: false,
          },
        ],
      },
      {
        enabled: true,
        directions: { north: true, south: false, east: true, west: true },
        entities: [
          {
            name: "rusty blade",
            value: 4,
            type: "weapon",
            enabled: true,
            symbol: "sword",
            seen: false,
          },
          {
            name: "battered shield",
            value: 4,
            type: "weapon",
            enabled: false,
            symbol: "shield",
            seen: false,
          },
          {
            name: "green knight",
            value: 5,
            type: "enemy",
            enabled: false,
            symbol: "knight",
            seen: false,
          },
          {
            name: "evil skeleton",
            value: 4,
            type: "enemy",
            enabled: false,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: true,
            symbol: "ring",
            seen: false,
          },
          {
            name: "gold florin ",
            value: 4,
            type: "item",
            enabled: false,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "portcullis ",
            value: 4,
            type: "obstacle",
            enabled: true,
            symbol: "door",
            seen: false,
          },
          {
            name: "rusty lock",
            value: 6,
            type: "obstacle",
            enabled: true,
            symbol: "lock",
            seen: false,
          },
        ],
      },
      {
        enabled: true,
        directions: { north: false, south: true, east: true, west: true },
        entities: [
          {
            name: "rusty blade",
            value: 4,
            type: "weapon",
            enabled: true,
            symbol: "sword",
            seen: false,
          },
          {
            name: "battered shield",
            value: 4,
            type: "weapon",
            enabled: false,
            symbol: "shield",
            seen: false,
          },
          {
            name: "green knight",
            value: 5,
            type: "enemy",
            enabled: true,
            symbol: "knight",
            seen: false,
          },
          {
            name: "evil skeleton",
            value: 4,
            type: "enemy",
            enabled: true,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "gold florin ",
            value: 4,
            type: "item",
            enabled: true,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "portcullis ",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
          {
            name: "rusty lock",
            value: 6,
            type: "obstacle",
            enabled: false,
            symbol: "lock",
            seen: false,
          },
        ],
      },
      {
        enabled: true,
        directions: { north: false, south: false, east: false, west: true },
        entities: [
          {
            name: "rusty blade",
            value: 4,
            type: "weapon",
            enabled: false,
            symbol: "sword",
            seen: false,
          },
          {
            name: "battered shield",
            value: 4,
            type: "weapon",
            enabled: true,
            symbol: "shield",
            seen: false,
          },
          {
            name: "green knight",
            value: 5,
            type: "enemy",
            enabled: false,
            symbol: "knight",
            seen: false,
          },
          {
            name: "evil skeleton",
            value: 4,
            type: "enemy",
            enabled: true,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: true,
            symbol: "ring",
            seen: false,
          },
          {
            name: "gold florin ",
            value: 4,
            type: "item",
            enabled: false,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: true,
            symbol: "key",
            seen: false,
          },
          {
            name: "portcullis ",
            value: 4,
            type: "obstacle",
            enabled: true,
            symbol: "door",
            seen: false,
          },
          {
            name: "rusty lock",
            value: 6,
            type: "obstacle",
            enabled: true,
            symbol: "lock",
            seen: false,
          },
        ],
      },
    ],
    [
      {
        enabled: false,
        directions: { north: false, south: false, east: false, west: false },
        entities: [
          {
            name: "rusty blade",
            value: 4,
            type: "weapon",
            enabled: false,
            symbol: "sword",
            seen: false,
          },
          {
            name: "battered shield",
            value: 4,
            type: "weapon",
            enabled: false,
            symbol: "shield",
            seen: false,
          },
          {
            name: "green knight",
            value: 5,
            type: "enemy",
            enabled: false,
            symbol: "knight",
            seen: false,
          },
          {
            name: "evil skeleton",
            value: 4,
            type: "enemy",
            enabled: false,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "gold florin ",
            value: 4,
            type: "item",
            enabled: false,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "portcullis ",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
          {
            name: "rusty lock",
            value: 6,
            type: "obstacle",
            enabled: false,
            symbol: "lock",
            seen: false,
          },
        ],
      },
      {
        enabled: false,
        directions: { north: false, south: false, east: false, west: false },
        entities: [
          {
            name: "rusty blade",
            value: 4,
            type: "weapon",
            enabled: false,
            symbol: "sword",
            seen: false,
          },
          {
            name: "battered shield",
            value: 4,
            type: "weapon",
            enabled: false,
            symbol: "shield",
            seen: false,
          },
          {
            name: "green knight",
            value: 5,
            type: "enemy",
            enabled: false,
            symbol: "knight",
            seen: false,
          },
          {
            name: "evil skeleton",
            value: 4,
            type: "enemy",
            enabled: false,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "gold florin ",
            value: 4,
            type: "item",
            enabled: false,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "portcullis ",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
          {
            name: "rusty lock",
            value: 6,
            type: "obstacle",
            enabled: false,
            symbol: "lock",
            seen: false,
          },
        ],
      },
      {
        enabled: true,
        directions: { north: true, south: false, east: false, west: false },
        entities: [
          {
            name: "rusty blade",
            value: 4,
            type: "weapon",
            enabled: false,
            symbol: "sword",
            seen: false,
          },
          {
            name: "battered shield",
            value: 4,
            type: "weapon",
            enabled: false,
            symbol: "shield",
            seen: false,
          },
          {
            name: "green knight",
            value: 5,
            type: "enemy",
            enabled: false,
            symbol: "knight",
            seen: false,
          },
          {
            name: "evil skeleton",
            value: 4,
            type: "enemy",
            enabled: false,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "gold florin ",
            value: 4,
            type: "item",
            enabled: false,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "portcullis ",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
          {
            name: "rusty lock",
            value: 6,
            type: "obstacle",
            enabled: false,
            symbol: "lock",
            seen: false,
          },
        ],
      },
      {
        enabled: false,
        directions: { north: false, south: false, east: false, west: false },
        entities: [
          {
            name: "rusty blade",
            value: 4,
            type: "weapon",
            enabled: false,
            symbol: "sword",
            seen: false,
          },
          {
            name: "battered shield",
            value: 4,
            type: "weapon",
            enabled: false,
            symbol: "shield",
            seen: false,
          },
          {
            name: "green knight",
            value: 5,
            type: "enemy",
            enabled: false,
            symbol: "knight",
            seen: false,
          },
          {
            name: "evil skeleton",
            value: 4,
            type: "enemy",
            enabled: false,
            symbol: "skeleton",
            seen: false,
          },
          {
            name: "shiny ring",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "ring",
            seen: false,
          },
          {
            name: "gold florin ",
            value: 4,
            type: "item",
            enabled: false,
            symbol: "coin",
            seen: false,
          },
          {
            name: "skeleton key",
            value: 6,
            type: "item",
            enabled: false,
            symbol: "key",
            seen: false,
          },
          {
            name: "portcullis ",
            value: 4,
            type: "obstacle",
            enabled: false,
            symbol: "door",
            seen: false,
          },
          {
            name: "rusty lock",
            value: 6,
            type: "obstacle",
            enabled: false,
            symbol: "lock",
            seen: false,
          },
        ],
      },
    ],
  ],
};
